version: '3.8'
services:
  database:
    image: mysql:8.0
    container_name: shortener_database
    volumes:
      - .docker/data/db:/var/lib/mysql:cached
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 96122325463
      MYSQL_DATABASE: url_shortener_db
      MYSQL_USER: url_shortener_user
      MYSQL_PASSWORD: codewebstudio
    ports:
      - 3306:3306
