spring:
  application:
    name: URL Shortener

  datasource:
    url: jdbc:mysql://localhost:3306/url_shortener_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 96122325463

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC







